name: tunis_village_app
description: Mobile app for the Tunis Village Booking Marketplace.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
